<?php

namespace Database\Seeders;
use App\Estado;
use App\Ciudad;
use Illuminate\Database\Seeder;

class VenezuelaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Estado	

		Estado::create(array( 'id_estado' => 1, 'estado' => 'Amazonas' ));
		Estado::create(array( 'id_estado' => 2, 'estado' => 'Anzoátegui' ));
		Estado::create(array( 'id_estado' => 3, 'estado' => 'Apure' ));
		Estado::create(array( 'id_estado' => 4, 'estado' => 'Aragua' ));
		Estado::create(array( 'id_estado' => 5, 'estado' => 'Barinas'));
		Estado::create(array( 'id_estado' => 6, 'estado' => 'Bolívar' ));
		Estado::create(array( 'id_estado' => 7, 'estado' => 'Carabobo' ));
		Estado::create(array( 'id_estado' => 8, 'estado' => 'Cojedes' ));
		Estado::create(array( 'id_estado' => 9, 'estado' => 'Delta Amacuro'));
		Estado::create(array( 'id_estado' => 10, 'estado' => 'Falcón'));
		Estado::create(array( 'id_estado' => 11, 'estado' => 'Guárico' ));
		Estado::create(array( 'id_estado' => 12, 'estado' => 'Lara' ));
		Estado::create(array( 'id_estado' => 13, 'estado' => 'Mérida'));
		Estado::create(array( 'id_estado' => 14, 'estado' => 'Miranda'));
		Estado::create(array( 'id_estado' => 15, 'estado' => 'Monagas' ));
		Estado::create(array( 'id_estado' => 16, 'estado' => 'Nueva Esparta'));
		Estado::create(array( 'id_estado' => 17, 'estado' => 'Portuguesa' ));
		Estado::create(array( 'id_estado' => 18, 'estado' => 'Sucre'));
		Estado::create(array( 'id_estado' => 19, 'estado' => 'Táchira' ));
		Estado::create(array( 'id_estado' => 20, 'estado' => 'Trujillo'));
		Estado::create(array( 'id_estado' => 21, 'estado' => 'Vargas' ));
		Estado::create(array( 'id_estado' => 22, 'estado' => 'Yaracuy' ));
		Estado::create(array( 'id_estado' => 23, 'estado' => 'Zulia' ));
		Estado::create(array( 'id_estado' => 24, 'estado' => 'Distrito Capital' ));
		Estado::create(array( 'id_estado' => 25, 'estado' => 'Dependencias Federales' ));

        //Ciudad

        /* CIUDADES */

		Ciudad::create(array( 'id_ciudad' => 1, 'id_estado' => 1,  'ciudad'=> 'Maroa' ));
		Ciudad::create(array( 'id_ciudad' => 2, 'id_estado' => 1, 'ciudad'=> 'Puerto Ayacucho' ));
		Ciudad::create(array( 'id_ciudad' => 3, 'id_estado' => 1, 'ciudad'=> 'San Fernando de Atabapo' ));
		Ciudad::create(array( 'id_ciudad' => 4, 'id_estado' => 2, 'ciudad'=> 'Anaco' ));
		Ciudad::create(array( 'id_ciudad' => 5, 'id_estado' => 2, 'ciudad'=> 'Aragua de Barcelona' ));
		Ciudad::create(array( 'id_ciudad' => 6, 'id_estado' => 2, 'ciudad'=> 'Barcelona' ));
		Ciudad::create(array( 'id_ciudad' => 7, 'id_estado' => 2, 'ciudad'=> 'Boca de Uchire' ));
		Ciudad::create(array( 'id_ciudad' => 8, 'id_estado' => 2, 'ciudad'=> 'Cantaura' ));
		Ciudad::create(array( 'id_ciudad' => 9, 'id_estado' => 2, 'ciudad'=> 'Clarines' ));
		Ciudad::create(array( 'id_ciudad' => 10, 'id_estado' => 2, 'ciudad'=> 'El Chaparro' ));
		Ciudad::create(array( 'id_ciudad' => 13, 'id_estado' => 2, 'ciudad'=> 'El Tigrito' ));
		Ciudad::create(array( 'id_ciudad' => 11, 'id_estado' => 2, 'ciudad'=> 'El Pao Anzoátegui' ));
		Ciudad::create(array( 'id_ciudad' => 14, 'id_estado' => 2, 'ciudad'=> 'Guanape' ));
		Ciudad::create(array( 'id_ciudad' => 17, 'id_estado' => 2, 'ciudad'=> 'Onoto' ));
		Ciudad::create(array( 'id_ciudad' => 18, 'id_estado' => 2, 'ciudad'=> 'Pariaguán' ));
		Ciudad::create(array( 'id_ciudad' => 19, 'id_estado' => 2, 'ciudad'=> 'Píritu' ));
		Ciudad::create(array( 'id_ciudad' => 16, 'id_estado' => 2, 'ciudad'=> 'Lechería' ));
		Ciudad::create(array( 'id_ciudad' => 20, 'id_estado' => 2, 'ciudad'=> 'Puerto La Cruz' ));
		Ciudad::create(array( 'id_ciudad' => 21, 'id_estado' => 2, 'ciudad'=> 'Puerto Píritu' ));
		Ciudad::create(array( 'id_ciudad' => 22, 'id_estado' => 2, 'ciudad'=> 'Sabana de Uchire' ));
		Ciudad::create(array( 'id_ciudad' => 23, 'id_estado' => 2, 'ciudad'=> 'San Mateo Anzoátegui' ));
		Ciudad::create(array( 'id_ciudad' => 12, 'id_estado' => 2, 'ciudad'=> 'El Tigre' ));
		Ciudad::create(array( 'id_ciudad' => 24, 'id_estado' => 2, 'ciudad'=> 'San Pablo Anzoátegui' ));
		Ciudad::create(array( 'id_ciudad' => 25, 'id_estado' => 2, 'ciudad'=> 'San Tomé' ));
		Ciudad::create(array( 'id_ciudad' => 26, 'id_estado' => 2, 'ciudad'=> 'Santa Ana de Anzoátegui' ));
		Ciudad::create(array( 'id_ciudad' => 15, 'id_estado' => 2, 'ciudad'=> 'Guanta' ));
		Ciudad::create(array( 'id_ciudad' => 27, 'id_estado' => 2, 'ciudad'=> 'Santa Fe Anzoátegui' ));
		Ciudad::create(array( 'id_ciudad' => 28, 'id_estado' => 2, 'ciudad'=> 'Santa Rosa' ));
		Ciudad::create(array( 'id_ciudad' => 29, 'id_estado' => 2, 'ciudad'=> 'Soledad' ));
		Ciudad::create(array( 'id_ciudad' => 30, 'id_estado' => 2, 'ciudad'=> 'Urica' ));
		Ciudad::create(array( 'id_ciudad' => 31, 'id_estado' => 2, 'ciudad'=> 'Valle de Guanape' ));
		Ciudad::create(array( 'id_ciudad' => 43, 'id_estado' => 3, 'ciudad'=> 'Achaguas' ));
		Ciudad::create(array( 'id_ciudad' => 44, 'id_estado' => 3, 'ciudad'=> 'Biruaca' ));
		Ciudad::create(array( 'id_ciudad' => 45, 'id_estado' => 3, 'ciudad'=> 'Bruzual' ));
		Ciudad::create(array( 'id_ciudad' => 46, 'id_estado' => 3, 'ciudad'=> 'El Amparo' ));
		Ciudad::create(array( 'id_ciudad' => 47, 'id_estado' => 3, 'ciudad'=> 'El Nula' ));
		Ciudad::create(array( 'id_ciudad' => 48, 'id_estado' => 3, 'ciudad'=> 'Elorza' ));
		Ciudad::create(array( 'id_ciudad' => 49, 'id_estado' => 3, 'ciudad'=> 'Guasdualito' ));
		Ciudad::create(array( 'id_ciudad' => 50, 'id_estado' => 3, 'ciudad'=> 'Mantecal' ));
		Ciudad::create(array( 'id_ciudad' => 51, 'id_estado' => 3, 'ciudad'=> 'Puerto Páez' ));
		Ciudad::create(array( 'id_ciudad' => 52, 'id_estado' => 3, 'ciudad'=> 'San Fernando de Apure' ));
		Ciudad::create(array( 'id_ciudad' => 53, 'id_estado' => 3, 'ciudad'=> 'San Juan de Payara' ));
		Ciudad::create(array( 'id_ciudad' => 54, 'id_estado' => 4, 'ciudad'=> 'Barbacoas' ));
		Ciudad::create(array( 'id_ciudad' => 55, 'id_estado' => 4, 'ciudad'=> 'Cagua' ));
		Ciudad::create(array( 'id_ciudad' => 56, 'id_estado' => 4, 'ciudad'=> 'Camatagua' ));
		Ciudad::create(array( 'id_ciudad' => 58, 'id_estado' => 4, 'ciudad'=> 'Choroní' ));
		Ciudad::create(array( 'id_ciudad' => 59, 'id_estado' => 4, 'ciudad'=> 'Colonia Tovar' ));
		Ciudad::create(array( 'id_ciudad' => 60, 'id_estado' => 4, 'ciudad'=> 'El Consejo' ));
		Ciudad::create(array( 'id_ciudad' => 61, 'id_estado' => 4, 'ciudad'=> 'La Victoria' ));
		Ciudad::create(array( 'id_ciudad' => 62, 'id_estado' => 4, 'ciudad'=> 'Las Tejerías' ));
		Ciudad::create(array( 'id_ciudad' => 63, 'id_estado' => 4, 'ciudad'=> 'Magdaleno' ));
		Ciudad::create(array( 'id_ciudad' => 64, 'id_estado' => 4, 'ciudad'=> 'Maracay' ));
		Ciudad::create(array( 'id_ciudad' => 65, 'id_estado' => 4, 'ciudad'=> 'Ocumare de La Costa' ));
		Ciudad::create(array( 'id_ciudad' => 66, 'id_estado' => 4, 'ciudad'=> 'Palo Negro' ));
		Ciudad::create(array( 'id_ciudad' => 67, 'id_estado' => 4, 'ciudad'=> 'San Casimiro' ));
		Ciudad::create(array( 'id_ciudad' => 68, 'id_estado' => 4, 'ciudad'=> 'San Mateo' ));
		Ciudad::create(array( 'id_ciudad' => 69, 'id_estado' => 4, 'ciudad'=> 'San Sebastián' ));
		Ciudad::create(array( 'id_ciudad' => 70, 'id_estado' => 4, 'ciudad'=> 'Santa Cruz de Aragua' ));
		Ciudad::create(array( 'id_ciudad' => 71, 'id_estado' => 4, 'ciudad'=> 'Tocorón' ));
		Ciudad::create(array( 'id_ciudad' => 72, 'id_estado' => 4, 'ciudad'=> 'Turmero' ));
		Ciudad::create(array( 'id_ciudad' => 73, 'id_estado' => 4, 'ciudad'=> 'Villa de Cura' ));
		Ciudad::create(array( 'id_ciudad' => 74, 'id_estado' => 4, 'ciudad'=> 'Zuata' ));
		Ciudad::create(array( 'id_ciudad' => 75, 'id_estado' => 5, 'ciudad'=> 'Barinas' ));
		Ciudad::create(array( 'id_ciudad' => 76, 'id_estado' => 5, 'ciudad'=> 'Barinitas' ));
		Ciudad::create(array( 'id_ciudad' => 77, 'id_estado' => 5, 'ciudad'=> 'Barrancas' ));
		Ciudad::create(array( 'id_ciudad' => 78, 'id_estado' => 5, 'ciudad'=> 'Calderas' ));
		Ciudad::create(array( 'id_ciudad' => 79, 'id_estado' => 5, 'ciudad'=> 'Capitanejo' ));
		Ciudad::create(array( 'id_ciudad' => 80, 'id_estado' => 5, 'ciudad'=> 'Ciudad Bolivia' ));
		Ciudad::create(array( 'id_ciudad' => 81, 'id_estado' => 5, 'ciudad'=> 'El Cantón' ));
		Ciudad::create(array( 'id_ciudad' => 82, 'id_estado' => 5, 'ciudad'=> 'Las Veguitas' ));
		Ciudad::create(array( 'id_ciudad' => 83, 'id_estado' => 5, 'ciudad'=> 'Libertad de Barinas' ));
		Ciudad::create(array( 'id_ciudad' => 84, 'id_estado' => 5, 'ciudad'=> 'Sabaneta' ));
		Ciudad::create(array( 'id_ciudad' => 85, 'id_estado' => 5, 'ciudad'=> 'Santa Bárbara de Barinas' ));
		Ciudad::create(array( 'id_ciudad' => 86, 'id_estado' => 5, 'ciudad'=> 'Socopó' ));
		Ciudad::create(array( 'id_ciudad' => 87, 'id_estado' => 6, 'ciudad'=> 'Caicara del Orinoco' ));
		Ciudad::create(array( 'id_ciudad' => 88, 'id_estado' => 6, 'ciudad'=> 'Canaima' ));
		Ciudad::create(array( 'id_ciudad' => 89, 'id_estado' => 6, 'ciudad'=> 'Ciudad Bolívar' ));
		Ciudad::create(array( 'id_ciudad' => 90, 'id_estado' => 6, 'ciudad'=> 'Ciudad Piar' ));
		Ciudad::create(array( 'id_ciudad' => 91, 'id_estado' => 6, 'ciudad'=> 'El Callao' ));
		Ciudad::create(array( 'id_ciudad' => 92, 'id_estado' => 6, 'ciudad'=> 'El Dorado' ));
		Ciudad::create(array( 'id_ciudad' => 93, 'id_estado' => 6, 'ciudad'=> 'El Manteco' ));
		Ciudad::create(array( 'id_ciudad' => 94, 'id_estado' => 6, 'ciudad'=> 'El Palmar' ));
		Ciudad::create(array( 'id_ciudad' => 95, 'id_estado' => 6, 'ciudad'=> 'El Pao' ));
		Ciudad::create(array( 'id_ciudad' => 96, 'id_estado' => 6, 'ciudad'=> 'Guasipati' ));
		Ciudad::create(array( 'id_ciudad' => 97, 'id_estado' => 6, 'ciudad'=> 'Guri' ));
		Ciudad::create(array( 'id_ciudad' => 98, 'id_estado' => 6, 'ciudad'=> 'La Paragua' ));
		Ciudad::create(array( 'id_ciudad' => 99, 'id_estado' => 6, 'ciudad'=> 'Matanzas' ));
		Ciudad::create(array( 'id_ciudad' => 100, 'id_estado' => 6, 'ciudad'=> 'Puerto Ordaz' ));
		Ciudad::create(array( 'id_ciudad' => 101, 'id_estado' => 6, 'ciudad'=> 'San Félix' ));
		Ciudad::create(array( 'id_ciudad' => 102, 'id_estado' => 6, 'ciudad'=> 'Santa Elena de Uairén' ));
		Ciudad::create(array( 'id_ciudad' => 103, 'id_estado' => 6, 'ciudad'=> 'Tumeremo' ));
		Ciudad::create(array( 'id_ciudad' => 104, 'id_estado' => 6, 'ciudad'=> 'Unare' ));
		Ciudad::create(array( 'id_ciudad' => 105, 'id_estado' => 6, 'ciudad'=> 'Upata' ));
		Ciudad::create(array( 'id_ciudad' => 106, 'id_estado' => 7, 'ciudad'=> 'Bejuma' ));
		Ciudad::create(array( 'id_ciudad' => 107, 'id_estado' => 7, 'ciudad'=> 'Belén' ));
		Ciudad::create(array( 'id_ciudad' => 108, 'id_estado' => 7, 'ciudad'=> 'Campo de Carabobo' ));
		Ciudad::create(array( 'id_ciudad' => 109, 'id_estado' => 7, 'ciudad'=> 'Canoabo' ));
		Ciudad::create(array( 'id_ciudad' => 110, 'id_estado' => 7, 'ciudad'=> 'Central Tacarigua' ));
		Ciudad::create(array( 'id_ciudad' => 111, 'id_estado' => 7, 'ciudad'=> 'Chirgua' ));
		Ciudad::create(array( 'id_ciudad' => 112, 'id_estado' => 7, 'ciudad'=> 'Ciudad Alianza' ));
		Ciudad::create(array( 'id_ciudad' => 113, 'id_estado' => 7, 'ciudad'=> 'El Palito' ));
		Ciudad::create(array( 'id_ciudad' => 114, 'id_estado' => 7, 'ciudad'=> 'Guacara' ));
		Ciudad::create(array( 'id_ciudad' => 115, 'id_estado' => 7, 'ciudad'=> 'Guigue' ));
		Ciudad::create(array( 'id_ciudad' => 116, 'id_estado' => 7, 'ciudad'=> 'Las Trincheras' ));
		Ciudad::create(array( 'id_ciudad' => 117, 'id_estado' => 7, 'ciudad'=> 'Los Guayos' ));
		Ciudad::create(array( 'id_ciudad' => 118, 'id_estado' => 7, 'ciudad'=> 'Mariara' ));
		Ciudad::create(array( 'id_ciudad' => 119, 'id_estado' => 7, 'ciudad'=> 'Miranda' ));
		Ciudad::create(array( 'id_ciudad' => 120, 'id_estado' => 7, 'ciudad'=> 'Montalbán' ));
		Ciudad::create(array( 'id_ciudad' => 121, 'id_estado' => 7, 'ciudad'=> 'Morón' ));
		Ciudad::create(array( 'id_ciudad' => 122, 'id_estado' => 7, 'ciudad'=> 'Naguanagua' ));
		Ciudad::create(array( 'id_ciudad' => 123, 'id_estado' => 7, 'ciudad'=> 'Puerto Cabello' ));
		Ciudad::create(array( 'id_ciudad' => 124, 'id_estado' => 7, 'ciudad'=> 'San Joaquín' ));
		Ciudad::create(array( 'id_ciudad' => 125, 'id_estado' => 7, 'ciudad'=> 'Tocuyito' ));
		Ciudad::create(array( 'id_ciudad' => 126, 'id_estado' => 7, 'ciudad'=> 'Urama' ));
		Ciudad::create(array( 'id_ciudad' => 127, 'id_estado' => 7, 'ciudad'=> 'Valencia' ));
		Ciudad::create(array( 'id_ciudad' => 128, 'id_estado' => 7, 'ciudad'=> 'Vigirimita' ));
		Ciudad::create(array( 'id_ciudad' => 129, 'id_estado' => 8, 'ciudad'=> 'Aguirre' ));
		Ciudad::create(array( 'id_ciudad' => 130, 'id_estado' => 8, 'ciudad'=> 'Apartaderos Cojedes' ));
		Ciudad::create(array( 'id_ciudad' => 131, 'id_estado' => 8, 'ciudad'=> 'Arismendi' ));
		Ciudad::create(array( 'id_ciudad' => 132, 'id_estado' => 8, 'ciudad'=> 'Camuriquito' ));
		Ciudad::create(array( 'id_ciudad' => 133, 'id_estado' => 8, 'ciudad'=> 'El Baúl' ));
		Ciudad::create(array( 'id_ciudad' => 134, 'id_estado' => 8, 'ciudad'=> 'El Limón' ));
		Ciudad::create(array( 'id_ciudad' => 135, 'id_estado' => 8, 'ciudad'=> 'El Pao Cojedes' ));
		Ciudad::create(array( 'id_ciudad' => 136, 'id_estado' => 8, 'ciudad'=> 'El Socorro' ));
		Ciudad::create(array( 'id_ciudad' => 137, 'id_estado' => 8, 'ciudad'=> 'La Aguadita' ));
		Ciudad::create(array( 'id_ciudad' => 138, 'id_estado' => 8, 'ciudad'=> 'Las Vegas' ));
		Ciudad::create(array( 'id_ciudad' => 139, 'id_estado' => 8, 'ciudad'=> 'Libertad de Cojedes' ));
		Ciudad::create(array( 'id_ciudad' => 140, 'id_estado' => 8, 'ciudad'=> 'Mapuey' ));
		Ciudad::create(array( 'id_ciudad' => 141, 'id_estado' => 8, 'ciudad'=> 'Piñedo' ));
		Ciudad::create(array( 'id_ciudad' => 142, 'id_estado' => 8, 'ciudad'=> 'Samancito' ));
		Ciudad::create(array( 'id_ciudad' => 143, 'id_estado' => 8, 'ciudad'=> 'San Carlos' ));
		Ciudad::create(array( 'id_ciudad' => 144, 'id_estado' => 8, 'ciudad'=> 'Sucre' ));
		Ciudad::create(array( 'id_ciudad' => 145, 'id_estado' => 8, 'ciudad'=> 'Tinaco' ));
		Ciudad::create(array( 'id_ciudad' => 146, 'id_estado' => 8, 'ciudad'=> 'Tinaquillo' ));
		Ciudad::create(array( 'id_ciudad' => 147, 'id_estado' => 8, 'ciudad'=> 'Vallecito' ));
		Ciudad::create(array( 'id_ciudad' => 148, 'id_estado' => 9, 'ciudad'=> 'Tucupita' ));
		Ciudad::create(array( 'id_ciudad' => 149, 'id_estado' => 24, 'ciudad'=> 'Caracas' ));
		Ciudad::create(array( 'id_ciudad' => 150, 'id_estado' => 24, 'ciudad'=> 'El Junquito' ));
		Ciudad::create(array( 'id_ciudad' => 151, 'id_estado' => 10, 'ciudad'=> 'Adícora' ));
		Ciudad::create(array( 'id_ciudad' => 152, 'id_estado' => 10, 'ciudad'=> 'Boca de Aroa' ));
		Ciudad::create(array( 'id_ciudad' => 153, 'id_estado' => 10, 'ciudad'=> 'Cabure' ));
		Ciudad::create(array( 'id_ciudad' => 154, 'id_estado' => 10, 'ciudad'=> 'Capadare' ));
		Ciudad::create(array( 'id_ciudad' => 155, 'id_estado' => 10, 'ciudad'=> 'Capatárida' ));
		Ciudad::create(array( 'id_ciudad' => 156, 'id_estado' => 10, 'ciudad'=> 'Chichiriviche' ));
		Ciudad::create(array( 'id_ciudad' => 157, 'id_estado' => 10, 'ciudad'=> 'Churuguara' ));
		Ciudad::create(array( 'id_ciudad' => 158, 'id_estado' => 10, 'ciudad'=> 'Coro' ));
		Ciudad::create(array( 'id_ciudad' => 159, 'id_estado' => 10, 'ciudad'=> 'Cumarebo' ));
		Ciudad::create(array( 'id_ciudad' => 160, 'id_estado' => 10, 'ciudad'=> 'Dabajuro' ));
		Ciudad::create(array( 'id_ciudad' => 161, 'id_estado' => 10, 'ciudad'=> 'Judibana' ));
		Ciudad::create(array( 'id_ciudad' => 162, 'id_estado' => 10, 'ciudad'=> 'La Cruz de Taratara' ));
		Ciudad::create(array( 'id_ciudad' => 163, 'id_estado' => 10, 'ciudad'=> 'La Vela de Coro' ));
		Ciudad::create(array( 'id_ciudad' => 164, 'id_estado' => 10, 'ciudad'=> 'Los Taques' ));
		Ciudad::create(array( 'id_ciudad' => 165, 'id_estado' => 10, 'ciudad'=> 'Maparari' ));
		Ciudad::create(array( 'id_ciudad' => 166, 'id_estado' => 10, 'ciudad'=> 'Mene de Mauroa' ));
		Ciudad::create(array( 'id_ciudad' => 167, 'id_estado' => 10, 'ciudad'=> 'Mirimire' ));
		Ciudad::create(array( 'id_ciudad' => 168, 'id_estado' => 10, 'ciudad'=> 'Pedregal' ));
		Ciudad::create(array( 'id_ciudad' => 169, 'id_estado' => 10, 'ciudad'=> 'Píritu Falcón' ));
		Ciudad::create(array( 'id_ciudad' => 170, 'id_estado' => 10, 'ciudad'=> 'Pueblo Nuevo Falcón' ));
		Ciudad::create(array( 'id_ciudad' => 171, 'id_estado' => 10, 'ciudad'=> 'Puerto Cumarebo' ));
		Ciudad::create(array( 'id_ciudad' => 172, 'id_estado' => 10, 'ciudad'=> 'Punta Cardón' ));
		Ciudad::create(array( 'id_ciudad' => 173, 'id_estado' => 10, 'ciudad'=> 'Punto Fijo' ));
		Ciudad::create(array( 'id_ciudad' => 174, 'id_estado' => 10, 'ciudad'=> 'San Juan de Los Cayos' ));
		Ciudad::create(array( 'id_ciudad' => 175, 'id_estado' => 10, 'ciudad'=> 'San Luis' ));
		Ciudad::create(array( 'id_ciudad' => 176, 'id_estado' => 10, 'ciudad'=> 'Santa Ana Falcón' ));
		Ciudad::create(array( 'id_ciudad' => 177, 'id_estado' => 10, 'ciudad'=> 'Santa Cruz De Bucaral' ));
		Ciudad::create(array( 'id_ciudad' => 178, 'id_estado' => 10, 'ciudad'=> 'Tocopero' ));
		Ciudad::create(array( 'id_ciudad' => 179, 'id_estado' => 10, 'ciudad'=> 'Tocuyo de La Costa' ));
		Ciudad::create(array( 'id_ciudad' => 180, 'id_estado' => 10, 'ciudad'=> 'Tucacas' ));
		Ciudad::create(array( 'id_ciudad' => 181, 'id_estado' => 10, 'ciudad'=> 'Yaracal' ));
		Ciudad::create(array( 'id_ciudad' => 182, 'id_estado' => 11, 'ciudad'=> 'Altagracia de Orituco' ));
		Ciudad::create(array( 'id_ciudad' => 183, 'id_estado' => 11, 'ciudad'=> 'Cabruta' ));
		Ciudad::create(array( 'id_ciudad' => 184, 'id_estado' => 11, 'ciudad'=> 'Calabozo' ));
		Ciudad::create(array( 'id_ciudad' => 185, 'id_estado' => 11, 'ciudad'=> 'Camaguán' ));
		Ciudad::create(array( 'id_ciudad' => 196, 'id_estado' => 11, 'ciudad'=> 'Chaguaramas Guárico' ));
		Ciudad::create(array( 'id_ciudad' => 197, 'id_estado' => 11, 'ciudad'=> 'El Socorro' ));
		Ciudad::create(array( 'id_ciudad' => 198, 'id_estado' => 11, 'ciudad'=> 'El Sombrero' ));
		Ciudad::create(array( 'id_ciudad' => 199, 'id_estado' => 11, 'ciudad'=> 'Las Mercedes de Los Llanos' ));
		Ciudad::create(array( 'id_ciudad' => 200, 'id_estado' => 11, 'ciudad'=> 'Lezama' ));
		Ciudad::create(array( 'id_ciudad' => 201, 'id_estado' => 11, 'ciudad'=> 'Onoto' ));
		Ciudad::create(array( 'id_ciudad' => 202, 'id_estado' => 11, 'ciudad'=> 'Ortíz' ));
		Ciudad::create(array( 'id_ciudad' => 203, 'id_estado' => 11, 'ciudad'=> 'San José de Guaribe' ));
		Ciudad::create(array( 'id_ciudad' => 204, 'id_estado' => 11, 'ciudad'=> 'San Juan de Los Morros' ));
		Ciudad::create(array( 'id_ciudad' => 205, 'id_estado' => 11, 'ciudad'=> 'San Rafael de Laya' ));
		Ciudad::create(array( 'id_ciudad' => 206, 'id_estado' => 11, 'ciudad'=> 'Santa María de Ipire' ));
		Ciudad::create(array( 'id_ciudad' => 207, 'id_estado' => 11, 'ciudad'=> 'Tucupido' ));
		Ciudad::create(array( 'id_ciudad' => 208, 'id_estado' => 11, 'ciudad'=> 'Valle de La Pascua' ));
		Ciudad::create(array( 'id_ciudad' => 209, 'id_estado' => 11, 'ciudad'=> 'Zaraza' ));
		Ciudad::create(array( 'id_ciudad' => 210, 'id_estado' => 12, 'ciudad'=> 'Aguada Grande' ));
		Ciudad::create(array( 'id_ciudad' => 211, 'id_estado' => 12, 'ciudad'=> 'Atarigua' ));
		Ciudad::create(array( 'id_ciudad' => 212, 'id_estado' => 12, 'ciudad'=> 'Barquisimeto' ));
		Ciudad::create(array( 'id_ciudad' => 213, 'id_estado' => 12, 'ciudad'=> 'Bobare' ));
		Ciudad::create(array( 'id_ciudad' => 214, 'id_estado' => 12, 'ciudad'=> 'Cabudare' ));
		Ciudad::create(array( 'id_ciudad' => 215, 'id_estado' => 12, 'ciudad'=> 'Carora' ));
		Ciudad::create(array( 'id_ciudad' => 216, 'id_estado' => 12, 'ciudad'=> 'Cubiro' ));
		Ciudad::create(array( 'id_ciudad' => 217, 'id_estado' => 12, 'ciudad'=> 'Cují' ));
		Ciudad::create(array( 'id_ciudad' => 218, 'id_estado' => 12, 'ciudad'=> 'Duaca' ));
		Ciudad::create(array( 'id_ciudad' => 219, 'id_estado' => 12, 'ciudad'=> 'El Manzano' ));
		Ciudad::create(array( 'id_ciudad' => 220, 'id_estado' => 12, 'ciudad'=> 'El Tocuyo' ));
		Ciudad::create(array( 'id_ciudad' => 221, 'id_estado' => 12, 'ciudad'=> 'Guaríco' ));
		Ciudad::create(array( 'id_ciudad' => 222, 'id_estado' => 12, 'ciudad'=> 'Humocaro Alto' ));
		Ciudad::create(array( 'id_ciudad' => 223, 'id_estado' => 12, 'ciudad'=> 'Humocaro Bajo' ));
		Ciudad::create(array( 'id_ciudad' => 224, 'id_estado' => 12, 'ciudad'=> 'La Miel' ));
		Ciudad::create(array( 'id_ciudad' => 225, 'id_estado' => 12, 'ciudad'=> 'Moroturo' ));
		Ciudad::create(array( 'id_ciudad' => 226, 'id_estado' => 12, 'ciudad'=> 'Quíbor' ));
		Ciudad::create(array( 'id_ciudad' => 227, 'id_estado' => 12, 'ciudad'=> 'Río Claro' ));
		Ciudad::create(array( 'id_ciudad' => 228, 'id_estado' => 12, 'ciudad'=> 'Sanare' ));
		Ciudad::create(array( 'id_ciudad' => 229, 'id_estado' => 12, 'ciudad'=> 'Santa Inés' ));
		Ciudad::create(array( 'id_ciudad' => 230, 'id_estado' => 12, 'ciudad'=> 'Sarare' ));
		Ciudad::create(array( 'id_ciudad' => 231, 'id_estado' => 12, 'ciudad'=> 'Siquisique' ));
		Ciudad::create(array( 'id_ciudad' => 232, 'id_estado' => 12, 'ciudad'=> 'Tintorero' ));
		Ciudad::create(array( 'id_ciudad' => 233, 'id_estado' => 13, 'ciudad'=> 'Apartaderos Mérida' ));
		Ciudad::create(array( 'id_ciudad' => 234, 'id_estado' => 13, 'ciudad'=> 'Arapuey' ));
		Ciudad::create(array( 'id_ciudad' => 235, 'id_estado' => 13, 'ciudad'=> 'Bailadores' ));
		Ciudad::create(array( 'id_ciudad' => 236, 'id_estado' => 13, 'ciudad'=> 'Caja Seca' ));
		Ciudad::create(array( 'id_ciudad' => 237, 'id_estado' => 13, 'ciudad'=> 'Canaguá' ));
		Ciudad::create(array( 'id_ciudad' => 238, 'id_estado' => 13, 'ciudad'=> 'Chachopo' ));
		Ciudad::create(array( 'id_ciudad' => 239, 'id_estado' => 13, 'ciudad'=> 'Chiguara' ));
		Ciudad::create(array( 'id_ciudad' => 240, 'id_estado' => 13, 'ciudad'=> 'Ejido' ));
		Ciudad::create(array( 'id_ciudad' => 241, 'id_estado' => 13, 'ciudad'=> 'El Vigía' ));
		Ciudad::create(array( 'id_ciudad' => 242, 'id_estado' => 13, 'ciudad'=> 'La Azulita' ));
		Ciudad::create(array( 'id_ciudad' => 243, 'id_estado' => 13, 'ciudad'=> 'La Playa' ));
		Ciudad::create(array( 'id_ciudad' => 244, 'id_estado' => 13, 'ciudad'=> 'Lagunillas Mérida' ));
		Ciudad::create(array( 'id_ciudad' => 245, 'id_estado' => 13, 'ciudad'=> 'Mérida' ));
		Ciudad::create(array( 'id_ciudad' => 246, 'id_estado' => 13, 'ciudad'=> 'Mesa de Bolívar' ));
		Ciudad::create(array( 'id_ciudad' => 247, 'id_estado' => 13, 'ciudad'=> 'Mucuchíes' ));
		Ciudad::create(array( 'id_ciudad' => 248, 'id_estado' => 13, 'ciudad'=> 'Mucujepe' ));
		Ciudad::create(array( 'id_ciudad' => 249, 'id_estado' => 13, 'ciudad'=> 'Mucuruba' ));
		Ciudad::create(array( 'id_ciudad' => 250, 'id_estado' => 13, 'ciudad'=> 'Nueva Bolivia' ));
		Ciudad::create(array( 'id_ciudad' => 251, 'id_estado' => 13, 'ciudad'=> 'Palmarito' ));
		Ciudad::create(array( 'id_ciudad' => 252, 'id_estado' => 13, 'ciudad'=> 'Pueblo Llano' ));
		Ciudad::create(array( 'id_ciudad' => 253, 'id_estado' => 13, 'ciudad'=> 'Santa Cruz de Mora' ));
		Ciudad::create(array( 'id_ciudad' => 254, 'id_estado' => 13, 'ciudad'=> 'Santa Elena de Arenales' ));
		Ciudad::create(array( 'id_ciudad' => 255, 'id_estado' => 13, 'ciudad'=> 'Santo Domingo' ));
		Ciudad::create(array( 'id_ciudad' => 256, 'id_estado' => 13, 'ciudad'=> 'Tabáy' ));
		Ciudad::create(array( 'id_ciudad' => 257, 'id_estado' => 13, 'ciudad'=> 'Timotes' ));
		Ciudad::create(array( 'id_ciudad' => 258, 'id_estado' => 13, 'ciudad'=> 'Torondoy' ));
		Ciudad::create(array( 'id_ciudad' => 259, 'id_estado' => 13, 'ciudad'=> 'Tovar' ));
		Ciudad::create(array( 'id_ciudad' => 260, 'id_estado' => 13, 'ciudad'=> 'Tucani' ));
		Ciudad::create(array( 'id_ciudad' => 261, 'id_estado' => 13, 'ciudad'=> 'Zea' ));
		Ciudad::create(array( 'id_ciudad' => 262, 'id_estado' => 14, 'ciudad'=> 'Araguita' ));
		Ciudad::create(array( 'id_ciudad' => 263, 'id_estado' => 14, 'ciudad'=> 'Carrizal' ));
		Ciudad::create(array( 'id_ciudad' => 264, 'id_estado' => 14, 'ciudad'=> 'Caucagua' ));
		Ciudad::create(array( 'id_ciudad' => 265, 'id_estado' => 14, 'ciudad'=> 'Chaguaramas Miranda' ));
		Ciudad::create(array( 'id_ciudad' => 266, 'id_estado' => 14, 'ciudad'=> 'Charallave' ));
		Ciudad::create(array( 'id_ciudad' => 267, 'id_estado' => 14, 'ciudad'=> 'Chirimena' ));
		Ciudad::create(array( 'id_ciudad' => 268, 'id_estado' => 14, 'ciudad'=> 'Chuspa' ));
		Ciudad::create(array( 'id_ciudad' => 269, 'id_estado' => 14, 'ciudad'=> 'Cúa' ));
		Ciudad::create(array( 'id_ciudad' => 270, 'id_estado' => 14, 'ciudad'=> 'Cupira' ));
		Ciudad::create(array( 'id_ciudad' => 271, 'id_estado' => 14, 'ciudad'=> 'Curiepe' ));
		Ciudad::create(array( 'id_ciudad' => 272, 'id_estado' => 14, 'ciudad'=> 'El Guapo' ));
		Ciudad::create(array( 'id_ciudad' => 273, 'id_estado' => 14, 'ciudad'=> 'El Jarillo' ));
		Ciudad::create(array( 'id_ciudad' => 274, 'id_estado' => 14, 'ciudad'=> 'Filas de Mariche' ));
		Ciudad::create(array( 'id_ciudad' => 275, 'id_estado' => 14, 'ciudad'=> 'Guarenas' ));
		Ciudad::create(array( 'id_ciudad' => 276, 'id_estado' => 14, 'ciudad'=> 'Guatire' ));
		Ciudad::create(array( 'id_ciudad' => 277, 'id_estado' => 14, 'ciudad'=> 'Higuerote' ));
		Ciudad::create(array( 'id_ciudad' => 278, 'id_estado' => 14, 'ciudad'=> 'Los Anaucos' ));
		Ciudad::create(array( 'id_ciudad' => 279, 'id_estado' => 14, 'ciudad'=> 'Los Teques' ));
		Ciudad::create(array( 'id_ciudad' => 280, 'id_estado' => 14, 'ciudad'=> 'Ocumare del Tuy' ));
		Ciudad::create(array( 'id_ciudad' => 281, 'id_estado' => 14, 'ciudad'=> 'Panaquire' ));
		Ciudad::create(array( 'id_ciudad' => 282, 'id_estado' => 14, 'ciudad'=> 'Paracotos' ));
		Ciudad::create(array( 'id_ciudad' => 283, 'id_estado' => 14, 'ciudad'=> 'Río Chico' ));
		Ciudad::create(array( 'id_ciudad' => 284, 'id_estado' => 14, 'ciudad'=> 'San Antonio de Los Altos' ));
		Ciudad::create(array( 'id_ciudad' => 285, 'id_estado' => 14, 'ciudad'=> 'San Diego de Los Altos' ));
		Ciudad::create(array( 'id_ciudad' => 286, 'id_estado' => 14, 'ciudad'=> 'San Fernando del Guapo' ));
		Ciudad::create(array( 'id_ciudad' => 287, 'id_estado' => 14, 'ciudad'=> 'San Francisco de Yare' ));
		Ciudad::create(array( 'id_ciudad' => 288, 'id_estado' => 14, 'ciudad'=> 'San José de Los Altos' ));
		Ciudad::create(array( 'id_ciudad' => 289, 'id_estado' => 14, 'ciudad'=> 'San José de Río Chico' ));
		Ciudad::create(array( 'id_ciudad' => 290, 'id_estado' => 14, 'ciudad'=> 'San Pedro de Los Altos' ));
		Ciudad::create(array( 'id_ciudad' => 291, 'id_estado' => 14, 'ciudad'=> 'Santa Lucía' ));
		Ciudad::create(array( 'id_ciudad' => 292, 'id_estado' => 14, 'ciudad'=> 'Santa Teresa' ));
		Ciudad::create(array( 'id_ciudad' => 293, 'id_estado' => 14, 'ciudad'=> 'Tacarigua de La Laguna' ));
		Ciudad::create(array( 'id_ciudad' => 294, 'id_estado' => 14, 'ciudad'=> 'Tacarigua de Mamporal' ));
		Ciudad::create(array( 'id_ciudad' => 295, 'id_estado' => 14, 'ciudad'=> 'Tácata' ));
		Ciudad::create(array( 'id_ciudad' => 296, 'id_estado' => 14, 'ciudad'=> 'Turumo' ));
		Ciudad::create(array( 'id_ciudad' => 297, 'id_estado' => 15, 'ciudad'=> 'Aguasay' ));
		Ciudad::create(array( 'id_ciudad' => 298, 'id_estado' => 15, 'ciudad'=> 'Aragua de Maturín' ));
		Ciudad::create(array( 'id_ciudad' => 299, 'id_estado' => 15, 'ciudad'=> 'Barrancas del Orinoco' ));
		Ciudad::create(array( 'id_ciudad' => 300, 'id_estado' => 15, 'ciudad'=> 'Caicara de Maturín' ));
		Ciudad::create(array( 'id_ciudad' => 301, 'id_estado' => 15, 'ciudad'=> 'Caripe' ));
		Ciudad::create(array( 'id_ciudad' => 302, 'id_estado' => 15, 'ciudad'=> 'Caripito' ));
		Ciudad::create(array( 'id_ciudad' => 303, 'id_estado' => 15, 'ciudad'=> 'Chaguaramal' ));
		Ciudad::create(array( 'id_ciudad' => 305, 'id_estado' => 15, 'ciudad'=> 'Chaguaramas Monagas' ));
		Ciudad::create(array( 'id_ciudad' => 307, 'id_estado' => 15, 'ciudad'=> 'El Furrial' ));
		Ciudad::create(array( 'id_ciudad' => 308, 'id_estado' => 15, 'ciudad'=> 'El Tejero' ));
		Ciudad::create(array( 'id_ciudad' => 309, 'id_estado' => 15, 'ciudad'=> 'Jusepín' ));
		Ciudad::create(array( 'id_ciudad' => 310, 'id_estado' => 15, 'ciudad'=> 'La Toscana' ));
		Ciudad::create(array( 'id_ciudad' => 311, 'id_estado' => 15, 'ciudad'=> 'Maturín' ));
		Ciudad::create(array( 'id_ciudad' => 312, 'id_estado' => 15, 'ciudad'=> 'Miraflores' ));
		Ciudad::create(array( 'id_ciudad' => 313, 'id_estado' => 15, 'ciudad'=> 'Punta de Mata' ));
		Ciudad::create(array( 'id_ciudad' => 314, 'id_estado' => 15, 'ciudad'=> 'Quiriquire' ));
		Ciudad::create(array( 'id_ciudad' => 315, 'id_estado' => 15, 'ciudad'=> 'San Antonio de Maturín' ));
		Ciudad::create(array( 'id_ciudad' => 316, 'id_estado' => 15, 'ciudad'=> 'San Vicente Monagas' ));
		Ciudad::create(array( 'id_ciudad' => 317, 'id_estado' => 15, 'ciudad'=> 'Santa Bárbara' ));
		Ciudad::create(array( 'id_ciudad' => 318, 'id_estado' => 15, 'ciudad'=> 'Temblador' ));
		Ciudad::create(array( 'id_ciudad' => 319, 'id_estado' => 15, 'ciudad'=> 'Teresen' ));
		Ciudad::create(array( 'id_ciudad' => 320, 'id_estado' => 15, 'ciudad'=> 'Uracoa' ));
		Ciudad::create(array( 'id_ciudad' => 321, 'id_estado' => 16, 'ciudad'=> 'Altagracia' ));
		Ciudad::create(array( 'id_ciudad' => 322, 'id_estado' => 16, 'ciudad'=> 'Boca de Pozo' ));
		Ciudad::create(array( 'id_ciudad' => 323, 'id_estado' => 16, 'ciudad'=> 'Boca de Río' ));
		Ciudad::create(array( 'id_ciudad' => 324, 'id_estado' => 16, 'ciudad'=> 'El Espinal' ));
		Ciudad::create(array( 'id_ciudad' => 325, 'id_estado' => 16, 'ciudad'=> 'El Valle del Espíritu Santo' ));
		Ciudad::create(array( 'id_ciudad' => 326, 'id_estado' => 16, 'ciudad'=> 'El Yaque' ));
		Ciudad::create(array( 'id_ciudad' => 327, 'id_estado' => 16, 'ciudad'=> 'Juangriego' ));
		Ciudad::create(array( 'id_ciudad' => 328, 'id_estado' => 16, 'ciudad'=> 'La Asunción' ));
		Ciudad::create(array( 'id_ciudad' => 329, 'id_estado' => 16, 'ciudad'=> 'La Guardia' ));
		Ciudad::create(array( 'id_ciudad' => 330, 'id_estado' => 16, 'ciudad'=> 'Pampatar' ));
		Ciudad::create(array( 'id_ciudad' => 331, 'id_estado' => 16, 'ciudad'=> 'Porlamar' ));
		Ciudad::create(array( 'id_ciudad' => 332, 'id_estado' => 16, 'ciudad'=> 'Puerto Fermín' ));
		Ciudad::create(array( 'id_ciudad' => 333, 'id_estado' => 16, 'ciudad'=> 'Punta de Piedras' ));
		Ciudad::create(array( 'id_ciudad' => 334, 'id_estado' => 16, 'ciudad'=> 'San Francisco de Macanao' ));
		Ciudad::create(array( 'id_ciudad' => 335, 'id_estado' => 16, 'ciudad'=> 'San Juan Bautista' ));
		Ciudad::create(array( 'id_ciudad' => 336, 'id_estado' => 16, 'ciudad'=> 'San Pedro de Coche' ));
		Ciudad::create(array( 'id_ciudad' => 337, 'id_estado' => 16, 'ciudad'=> 'Santa Ana de Nueva Esparta' ));
		Ciudad::create(array( 'id_ciudad' => 338, 'id_estado' => 16, 'ciudad'=> 'Villa Rosa' ));
		Ciudad::create(array( 'id_ciudad' => 339, 'id_estado' => 17, 'ciudad'=> 'Acarigua' ));
		Ciudad::create(array( 'id_ciudad' => 340, 'id_estado' => 17, 'ciudad'=> 'Agua Blanca' ));
		Ciudad::create(array( 'id_ciudad' => 341, 'id_estado' => 17, 'ciudad'=> 'Araure' ));
		Ciudad::create(array( 'id_ciudad' => 342, 'id_estado' => 17, 'ciudad'=> 'Biscucuy' ));
		Ciudad::create(array( 'id_ciudad' => 343, 'id_estado' => 17, 'ciudad'=> 'Boconoito' ));
		Ciudad::create(array( 'id_ciudad' => 344, 'id_estado' => 17, 'ciudad'=> 'Campo Elías' ));
		Ciudad::create(array( 'id_ciudad' => 345, 'id_estado' => 17, 'ciudad'=> 'Chabasquén' ));
		Ciudad::create(array( 'id_ciudad' => 346, 'id_estado' => 17, 'ciudad'=> 'Guanare' ));
		Ciudad::create(array( 'id_ciudad' => 347, 'id_estado' => 17, 'ciudad'=> 'Guanarito' ));
		Ciudad::create(array( 'id_ciudad' => 348, 'id_estado' => 17, 'ciudad'=> 'La Aparición' ));
		Ciudad::create(array( 'id_ciudad' => 349, 'id_estado' => 17, 'ciudad'=> 'La Misión' ));
		Ciudad::create(array( 'id_ciudad' => 350, 'id_estado' => 17, 'ciudad'=> 'Mesa de Cavacas' ));
		Ciudad::create(array( 'id_ciudad' => 351, 'id_estado' => 17, 'ciudad'=> 'Ospino' ));
		Ciudad::create(array( 'id_ciudad' => 352, 'id_estado' => 17, 'ciudad'=> 'Papelón' ));
		Ciudad::create(array( 'id_ciudad' => 353, 'id_estado' => 17, 'ciudad'=> 'Payara' ));
		Ciudad::create(array( 'id_ciudad' => 354, 'id_estado' => 17, 'ciudad'=> 'Pimpinela' ));
		Ciudad::create(array( 'id_ciudad' => 355, 'id_estado' => 17, 'ciudad'=> 'Píritu de Portuguesa' ));
		Ciudad::create(array( 'id_ciudad' => 356, 'id_estado' => 17, 'ciudad'=> 'San Rafael de Onoto' ));
		Ciudad::create(array( 'id_ciudad' => 357, 'id_estado' => 17, 'ciudad'=> 'Santa Rosalía' ));
		Ciudad::create(array( 'id_ciudad' => 358, 'id_estado' => 17, 'ciudad'=> 'Turén' ));
		Ciudad::create(array( 'id_ciudad' => 359, 'id_estado' => 18, 'ciudad'=> 'Altos de Sucre' ));
		Ciudad::create(array( 'id_ciudad' => 360, 'id_estado' => 18, 'ciudad'=> 'Araya' ));
		Ciudad::create(array( 'id_ciudad' => 361, 'id_estado' => 18, 'ciudad'=> 'Cariaco' ));
		Ciudad::create(array( 'id_ciudad' => 362, 'id_estado' => 18, 'ciudad'=> 'Carúpano' ));
		Ciudad::create(array( 'id_ciudad' => 363, 'id_estado' => 18, 'ciudad'=> 'Casanay' ));
		Ciudad::create(array( 'id_ciudad' => 364, 'id_estado' => 18, 'ciudad'=> 'Cumaná' ));
		Ciudad::create(array( 'id_ciudad' => 365, 'id_estado' => 18, 'ciudad'=> 'Cumanacoa' ));
		Ciudad::create(array( 'id_ciudad' => 366, 'id_estado' => 18, 'ciudad'=> 'El Morro Puerto Santo' ));
		Ciudad::create(array( 'id_ciudad' => 367, 'id_estado' => 18, 'ciudad'=> 'El Pilar' ));
		Ciudad::create(array( 'id_ciudad' => 368, 'id_estado' => 18, 'ciudad'=> 'El Poblado' ));
		Ciudad::create(array( 'id_ciudad' => 369, 'id_estado' => 18, 'ciudad'=> 'Guaca' ));
		Ciudad::create(array( 'id_ciudad' => 370, 'id_estado' => 18, 'ciudad'=> 'Guiria' ));
		Ciudad::create(array( 'id_ciudad' => 371, 'id_estado' => 18, 'ciudad'=> 'Irapa' ));
		Ciudad::create(array( 'id_ciudad' => 372, 'id_estado' => 18, 'ciudad'=> 'Manicuare' ));
		Ciudad::create(array( 'id_ciudad' => 373, 'id_estado' => 18, 'ciudad'=> 'Mariguitar' ));
		Ciudad::create(array( 'id_ciudad' => 374, 'id_estado' => 18, 'ciudad'=> 'Río Caribe' ));
		Ciudad::create(array( 'id_ciudad' => 375, 'id_estado' => 18, 'ciudad'=> 'San Antonio del Golfo' ));
		Ciudad::create(array( 'id_ciudad' => 376, 'id_estado' => 18, 'ciudad'=> 'San José de Aerocuar' ));
		Ciudad::create(array( 'id_ciudad' => 377, 'id_estado' => 18, 'ciudad'=> 'San Vicente de Sucre' ));
		Ciudad::create(array( 'id_ciudad' => 378, 'id_estado' => 18, 'ciudad'=> 'Santa Fe de Sucre' ));
		Ciudad::create(array( 'id_ciudad' => 379, 'id_estado' => 18, 'ciudad'=> 'Tunapuy' ));
		Ciudad::create(array( 'id_ciudad' => 380, 'id_estado' => 18, 'ciudad'=> 'Yaguaraparo' ));
		Ciudad::create(array( 'id_ciudad' => 381, 'id_estado' => 18, 'ciudad'=> 'Yoco' ));
		Ciudad::create(array( 'id_ciudad' => 382, 'id_estado' => 19, 'ciudad'=> 'Abejales' ));
		Ciudad::create(array( 'id_ciudad' => 383, 'id_estado' => 19, 'ciudad'=> 'Borota' ));
		Ciudad::create(array( 'id_ciudad' => 384, 'id_estado' => 19, 'ciudad'=> 'Bramon' ));
		Ciudad::create(array( 'id_ciudad' => 385, 'id_estado' => 19, 'ciudad'=> 'Capacho' ));
		Ciudad::create(array( 'id_ciudad' => 386, 'id_estado' => 19, 'ciudad'=> 'Colón' ));
		Ciudad::create(array( 'id_ciudad' => 387, 'id_estado' => 19, 'ciudad'=> 'Coloncito' ));
		Ciudad::create(array( 'id_ciudad' => 388, 'id_estado' => 19, 'ciudad'=> 'Cordero' ));
		Ciudad::create(array( 'id_ciudad' => 389, 'id_estado' => 19, 'ciudad'=> 'El Cobre' ));
		Ciudad::create(array( 'id_ciudad' => 390, 'id_estado' => 19, 'ciudad'=> 'El Pinal' ));
		Ciudad::create(array( 'id_ciudad' => 391, 'id_estado' => 19, 'ciudad'=> 'Independencia' ));
		Ciudad::create(array( 'id_ciudad' => 392, 'id_estado' => 19, 'ciudad'=> 'La Fría' ));
		Ciudad::create(array( 'id_ciudad' => 393, 'id_estado' => 19, 'ciudad'=> 'La Grita' ));
		Ciudad::create(array( 'id_ciudad' => 394, 'id_estado' => 19, 'ciudad'=> 'La Pedrera' ));
		Ciudad::create(array( 'id_ciudad' => 395, 'id_estado' => 19, 'ciudad'=> 'La Tendida' ));
		Ciudad::create(array( 'id_ciudad' => 396, 'id_estado' => 19, 'ciudad'=> 'Las Delicias' ));
		Ciudad::create(array( 'id_ciudad' => 397, 'id_estado' => 19, 'ciudad'=> 'Las Hernández' ));
		Ciudad::create(array( 'id_ciudad' => 398, 'id_estado' => 19, 'ciudad'=> 'Lobatera' ));
		Ciudad::create(array( 'id_ciudad' => 399, 'id_estado' => 19, 'ciudad'=> 'Michelena' ));
		Ciudad::create(array( 'id_ciudad' => 400, 'id_estado' => 19, 'ciudad'=> 'Palmira' ));
		Ciudad::create(array( 'id_ciudad' => 401, 'id_estado' => 19, 'ciudad'=> 'Pregonero' ));
		Ciudad::create(array( 'id_ciudad' => 402, 'id_estado' => 19, 'ciudad'=> 'Queniquea' ));
		Ciudad::create(array( 'id_ciudad' => 403, 'id_estado' => 19, 'ciudad'=> 'Rubio' ));
		Ciudad::create(array( 'id_ciudad' => 404, 'id_estado' => 19, 'ciudad'=> 'San Antonio del Tachira' ));
		Ciudad::create(array( 'id_ciudad' => 405, 'id_estado' => 19, 'ciudad'=> 'San Cristobal' ));
		Ciudad::create(array( 'id_ciudad' => 406, 'id_estado' => 19, 'ciudad'=> 'San José de Bolívar' ));
		Ciudad::create(array( 'id_ciudad' => 407, 'id_estado' => 19, 'ciudad'=> 'San Josecito' ));
		Ciudad::create(array( 'id_ciudad' => 408, 'id_estado' => 19, 'ciudad'=> 'San Pedro del Río' ));
		Ciudad::create(array( 'id_ciudad' => 409, 'id_estado' => 19, 'ciudad'=> 'Santa Ana Táchira' ));
		Ciudad::create(array( 'id_ciudad' => 410, 'id_estado' => 19, 'ciudad'=> 'Seboruco' ));
		Ciudad::create(array( 'id_ciudad' => 411, 'id_estado' => 19, 'ciudad'=> 'Táriba' ));
		Ciudad::create(array( 'id_ciudad' => 412, 'id_estado' => 19, 'ciudad'=> 'Umuquena' ));
		Ciudad::create(array( 'id_ciudad' => 413, 'id_estado' => 19, 'ciudad'=> 'Ureña' ));
		Ciudad::create(array( 'id_ciudad' => 414, 'id_estado' => 20, 'ciudad'=> 'Batatal' ));
		Ciudad::create(array( 'id_ciudad' => 415, 'id_estado' => 20, 'ciudad'=> 'Betijoque' ));
		Ciudad::create(array( 'id_ciudad' => 416, 'id_estado' => 20, 'ciudad'=> 'Boconó' ));
		Ciudad::create(array( 'id_ciudad' => 417, 'id_estado' => 20, 'ciudad'=> 'Carache' ));
		Ciudad::create(array( 'id_ciudad' => 418, 'id_estado' => 20, 'ciudad'=> 'Chejende' ));
		Ciudad::create(array( 'id_ciudad' => 419, 'id_estado' => 20, 'ciudad'=> 'Cuicas' ));
		Ciudad::create(array( 'id_ciudad' => 420, 'id_estado' => 20, 'ciudad'=> 'El Dividive' ));
		Ciudad::create(array( 'id_ciudad' => 421, 'id_estado' => 20, 'ciudad'=> 'El Jaguito' ));
		Ciudad::create(array( 'id_ciudad' => 422, 'id_estado' => 20, 'ciudad'=> 'Escuque' ));
		Ciudad::create(array( 'id_ciudad' => 423, 'id_estado' => 20, 'ciudad'=> 'Isnotú' ));
		Ciudad::create(array( 'id_ciudad' => 424, 'id_estado' => 20, 'ciudad'=> 'Jajó' ));
		Ciudad::create(array( 'id_ciudad' => 425, 'id_estado' => 20, 'ciudad'=> 'La Ceiba' ));
		Ciudad::create(array( 'id_ciudad' => 426, 'id_estado' => 20, 'ciudad'=> 'La Concepción de Trujllo' ));
		Ciudad::create(array( 'id_ciudad' => 427, 'id_estado' => 20, 'ciudad'=> 'La Mesa de Esnujaque' ));
		Ciudad::create(array( 'id_ciudad' => 428, 'id_estado' => 20, 'ciudad'=> 'La Puerta' ));
		Ciudad::create(array( 'id_ciudad' => 429, 'id_estado' => 20, 'ciudad'=> 'La Quebrada' ));
		Ciudad::create(array( 'id_ciudad' => 430, 'id_estado' => 20, 'ciudad'=> 'Mendoza Fría' ));
		Ciudad::create(array( 'id_ciudad' => 431, 'id_estado' => 20, 'ciudad'=> 'Meseta de Chimpire' ));
		Ciudad::create(array( 'id_ciudad' => 432, 'id_estado' => 20, 'ciudad'=> 'Monay' ));
		Ciudad::create(array( 'id_ciudad' => 433, 'id_estado' => 20, 'ciudad'=> 'Motatán' ));
		Ciudad::create(array( 'id_ciudad' => 434, 'id_estado' => 20, 'ciudad'=> 'Pampán' ));
		Ciudad::create(array( 'id_ciudad' => 435, 'id_estado' => 20, 'ciudad'=> 'Pampanito' ));
		Ciudad::create(array( 'id_ciudad' => 436, 'id_estado' => 20, 'ciudad'=> 'Sabana de Mendoza' ));
		Ciudad::create(array( 'id_ciudad' => 437, 'id_estado' => 20, 'ciudad'=> 'San Lázaro' ));
		Ciudad::create(array( 'id_ciudad' => 438, 'id_estado' => 20, 'ciudad'=> 'Santa Ana de Trujillo' ));
		Ciudad::create(array( 'id_ciudad' => 439, 'id_estado' => 20, 'ciudad'=> 'Tostós' ));
		Ciudad::create(array( 'id_ciudad' => 440, 'id_estado' => 20, 'ciudad'=> 'Trujillo' ));
		Ciudad::create(array( 'id_ciudad' => 441, 'id_estado' => 20, 'ciudad'=> 'Valera' ));
		Ciudad::create(array( 'id_ciudad' => 442, 'id_estado' => 21, 'ciudad'=> 'Carayaca' ));
		Ciudad::create(array( 'id_ciudad' => 443, 'id_estado' => 21, 'ciudad'=> 'Litoral' ));
		Ciudad::create(array( 'id_ciudad' => 444, 'id_estado' => 25, 'ciudad'=> 'Archipiélago Los Roques' ));
		Ciudad::create(array( 'id_ciudad' => 445, 'id_estado' => 22, 'ciudad'=> 'Aroa' ));
		Ciudad::create(array( 'id_ciudad' => 446, 'id_estado' => 22, 'ciudad'=> 'Boraure' ));
		Ciudad::create(array( 'id_ciudad' => 447, 'id_estado' => 22, 'ciudad'=> 'Campo Elías de Yaracuy' ));
		Ciudad::create(array( 'id_ciudad' => 448, 'id_estado' => 22, 'ciudad'=> 'Chivacoa' ));
		Ciudad::create(array( 'id_ciudad' => 449, 'id_estado' => 22, 'ciudad'=> 'Cocorote' ));
		Ciudad::create(array( 'id_ciudad' => 450, 'id_estado' => 22, 'ciudad'=> 'Farriar' ));
		Ciudad::create(array( 'id_ciudad' => 451, 'id_estado' => 22, 'ciudad'=> 'Guama' ));
		Ciudad::create(array( 'id_ciudad' => 452, 'id_estado' => 22, 'ciudad'=> 'Marín' ));
		Ciudad::create(array( 'id_ciudad' => 453, 'id_estado' => 22, 'ciudad'=> 'Nirgua' ));
		Ciudad::create(array( 'id_ciudad' => 454, 'id_estado' => 22, 'ciudad'=> 'Sabana de Parra' ));
		Ciudad::create(array( 'id_ciudad' => 455, 'id_estado' => 22, 'ciudad'=> 'Salom' ));
		Ciudad::create(array( 'id_ciudad' => 456, 'id_estado' => 22, 'ciudad'=> 'San Felipe' ));
		Ciudad::create(array( 'id_ciudad' => 457, 'id_estado' => 22, 'ciudad'=> 'San Pablo de Yaracuy' ));
		Ciudad::create(array( 'id_ciudad' => 458, 'id_estado' => 22, 'ciudad'=> 'Urachiche' ));
		Ciudad::create(array( 'id_ciudad' => 459, 'id_estado' => 22, 'ciudad'=> 'Yaritagua' ));
		Ciudad::create(array( 'id_ciudad' => 460, 'id_estado' => 22, 'ciudad'=> 'Yumare' ));
		Ciudad::create(array( 'id_ciudad' => 461, 'id_estado' => 23, 'ciudad'=> 'Bachaquero' ));
		Ciudad::create(array( 'id_ciudad' => 462, 'id_estado' => 23, 'ciudad'=> 'Bobures' ));
		Ciudad::create(array( 'id_ciudad' => 463, 'id_estado' => 23, 'ciudad'=> 'Cabimas' ));
		Ciudad::create(array( 'id_ciudad' => 464, 'id_estado' => 23, 'ciudad'=> 'Campo Concepción' ));
		Ciudad::create(array( 'id_ciudad' => 465, 'id_estado' => 23, 'ciudad'=> 'Campo Mara' ));
		Ciudad::create(array( 'id_ciudad' => 466, 'id_estado' => 23, 'ciudad'=> 'Campo Rojo' ));
		Ciudad::create(array( 'id_ciudad' => 467, 'id_estado' => 23, 'ciudad'=> 'Carrasquero' ));
		Ciudad::create(array( 'id_ciudad' => 468, 'id_estado' => 23, 'ciudad'=> 'Casigua' ));
		Ciudad::create(array( 'id_ciudad' => 469, 'id_estado' => 23, 'ciudad'=> 'Chiquinquirá' ));
		Ciudad::create(array( 'id_ciudad' => 470, 'id_estado' => 23, 'ciudad'=> 'Ciudad Ojeda' ));
		Ciudad::create(array( 'id_ciudad' => 471, 'id_estado' => 23, 'ciudad'=> 'El Batey' ));
		Ciudad::create(array( 'id_ciudad' => 472, 'id_estado' => 23, 'ciudad'=> 'El Carmelo' ));
		Ciudad::create(array( 'id_ciudad' => 473, 'id_estado' => 23, 'ciudad'=> 'El Chivo' ));
		Ciudad::create(array( 'id_ciudad' => 474, 'id_estado' => 23, 'ciudad'=> 'El Guayabo' ));
		Ciudad::create(array( 'id_ciudad' => 475, 'id_estado' => 23, 'ciudad'=> 'El Mene' ));
		Ciudad::create(array( 'id_ciudad' => 476, 'id_estado' => 23, 'ciudad'=> 'El Venado' ));
		Ciudad::create(array( 'id_ciudad' => 477, 'id_estado' => 23, 'ciudad'=> 'Encontrados' ));
		Ciudad::create(array( 'id_ciudad' => 478, 'id_estado' => 23, 'ciudad'=> 'Gibraltar' ));
		Ciudad::create(array( 'id_ciudad' => 479, 'id_estado' => 23, 'ciudad'=> 'Isla de Toas' ));
		Ciudad::create(array( 'id_ciudad' => 480, 'id_estado' => 23, 'ciudad'=> 'La Concepción del Zulia' ));
		Ciudad::create(array( 'id_ciudad' => 481, 'id_estado' => 23, 'ciudad'=> 'La Paz' ));
		Ciudad::create(array( 'id_ciudad' => 482, 'id_estado' => 23, 'ciudad'=> 'La Sierrita' ));
		Ciudad::create(array( 'id_ciudad' => 483, 'id_estado' => 23, 'ciudad'=> 'Lagunillas del Zulia' ));
		Ciudad::create(array( 'id_ciudad' => 484, 'id_estado' => 23, 'ciudad'=> 'Las Piedras de Perijá' ));
		Ciudad::create(array( 'id_ciudad' => 485, 'id_estado' => 23, 'ciudad'=> 'Los Cortijos' ));
		Ciudad::create(array( 'id_ciudad' => 486, 'id_estado' => 23, 'ciudad'=> 'Machiques' ));
		Ciudad::create(array( 'id_ciudad' => 487, 'id_estado' => 23, 'ciudad'=> 'Maracaibo' ));
		Ciudad::create(array( 'id_ciudad' => 488, 'id_estado' => 23, 'ciudad'=> 'Mene Grande' ));
		Ciudad::create(array( 'id_ciudad' => 489, 'id_estado' => 23, 'ciudad'=> 'Palmarejo' ));
		Ciudad::create(array( 'id_ciudad' => 490, 'id_estado' => 23, 'ciudad'=> 'Paraguaipoa' ));
		Ciudad::create(array( 'id_ciudad' => 491, 'id_estado' => 23, 'ciudad'=> 'Potrerito' ));
		Ciudad::create(array( 'id_ciudad' => 492, 'id_estado' => 23, 'ciudad'=> 'Pueblo Nuevo del Zulia' ));
		Ciudad::create(array( 'id_ciudad' => 493, 'id_estado' => 23, 'ciudad'=> 'Puertos de Altagracia' ));
		Ciudad::create(array( 'id_ciudad' => 494, 'id_estado' => 23, 'ciudad'=> 'Punta Gorda' ));
		Ciudad::create(array( 'id_ciudad' => 495, 'id_estado' => 23, 'ciudad'=> 'Sabaneta de Palma' ));
		Ciudad::create(array( 'id_ciudad' => 496, 'id_estado' => 23, 'ciudad'=> 'San Francisco' ));
		Ciudad::create(array( 'id_ciudad' => 497, 'id_estado' => 23, 'ciudad'=> 'San José de Perijá' ));
		Ciudad::create(array( 'id_ciudad' => 498, 'id_estado' => 23, 'ciudad'=> 'San Rafael del Moján' ));
		Ciudad::create(array( 'id_ciudad' => 499, 'id_estado' => 23, 'ciudad'=> 'San Timoteo' ));
		Ciudad::create(array( 'id_ciudad' => 500, 'id_estado' => 23, 'ciudad'=> 'Santa Bárbara Del Zulia' ));
		Ciudad::create(array( 'id_ciudad' => 501, 'id_estado' => 23, 'ciudad'=> 'Santa Cruz de Mara' ));
		Ciudad::create(array( 'id_ciudad' => 502, 'id_estado' => 23, 'ciudad'=> 'Santa Cruz del Zulia' ));
		Ciudad::create(array( 'id_ciudad' => 503, 'id_estado' => 23, 'ciudad'=> 'Santa Rita' ));
		Ciudad::create(array( 'id_ciudad' => 504, 'id_estado' => 23, 'ciudad'=> 'Sinamaica' ));
		Ciudad::create(array( 'id_ciudad' => 505, 'id_estado' => 23, 'ciudad'=> 'Tamare' ));
		Ciudad::create(array( 'id_ciudad' => 506, 'id_estado' => 23, 'ciudad'=> 'Tía Juana' ));
		Ciudad::create(array( 'id_ciudad' => 507, 'id_estado' => 23, 'ciudad'=> 'Villa del Rosario' ));
		Ciudad::create(array( 'id_ciudad' => 508, 'id_estado' => 21, 'ciudad'=> 'La Guaira' ));
		Ciudad::create(array( 'id_ciudad' => 509, 'id_estado' => 21, 'ciudad'=> 'Catia La Mar' ));
		Ciudad::create(array( 'id_ciudad' => 510, 'id_estado' => 21, 'ciudad'=> 'Macuto' ));
		Ciudad::create(array( 'id_ciudad' => 511, 'id_estado' => 21, 'ciudad'=> 'Naiguatá' ));
		Ciudad::create(array( 'id_ciudad' => 512, 'id_estado' => 25, 'ciudad'=> 'Archipiélago Los Monjes' ));
		Ciudad::create(array( 'id_ciudad' => 513, 'id_estado' => 25, 'ciudad'=> 'Isla La Tortuga y Cayos adyacentes' ));
		Ciudad::create(array( 'id_ciudad' => 514, 'id_estado' => 25, 'ciudad'=> 'Isla La Sola' ));
		Ciudad::create(array( 'id_ciudad' => 515, 'id_estado' => 25, 'ciudad'=> 'Islas Los Testigos' ));
		Ciudad::create(array( 'id_ciudad' => 516, 'id_estado' => 25, 'ciudad'=> 'Islas Los Frailes' ));
		Ciudad::create(array( 'id_ciudad' => 517, 'id_estado' => 25, 'ciudad'=> 'Isla La Orchila' ));
		Ciudad::create(array( 'id_ciudad' => 518, 'id_estado' => 25, 'ciudad'=> 'Archipiélago Las Aves' ));
		Ciudad::create(array( 'id_ciudad' => 519, 'id_estado' => 25, 'ciudad'=> 'Isla de Aves' ));
		Ciudad::create(array( 'id_ciudad' => 520, 'id_estado' => 25, 'ciudad'=> 'Isla La Blanquilla' ));
		Ciudad::create(array( 'id_ciudad' => 521, 'id_estado' => 25, 'ciudad'=> 'Isla de Patos' ));
		Ciudad::create(array( 'id_ciudad' => 522, 'id_estado' => 25, 'ciudad'=> 'Islas Los Hermanos' ));
    }
}
